# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_user_guichet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_inferior', models.IntegerField(verbose_name='limite inferieure')),
                ('limit_superior', models.IntegerField(verbose_name='limite inferieure')),
                ('montant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transferts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom de l expediteur')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prenom de l expediteur')),
                ('montant', models.IntegerField(verbose_name='Montant')),
                ('datedepot', models.DateTimeField(verbose_name='date du depot')),
                ('MTCN', models.CharField(max_length=50, verbose_name='Code du Client')),
                ('commission', models.IntegerField()),
                ('last_namereceiver', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first_namereceiver', models.CharField(max_length=50)),
                ('cni', models.CharField(max_length=50, verbose_name='Carte National Identite')),
                ('datereceiver', models.DateTimeField(blank=True, null=True, verbose_name='Reicever Date')),
                ('guichet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Guichet')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.Tarifs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
