# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarifs',
            new_name='Tarif',
        ),
        migrations.RenameModel(
            old_name='Transferts',
            new_name='Transfert',
        ),
    ]
