# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_auto_20170531_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='tarif',
        ),
        migrations.AlterField(
            model_name='transfert',
            name='datedepot',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date du depot'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='datereceiver',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Reicever Date'),
        ),
    ]
