# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_user_guichet'),
        ('transfers', '0003_auto_20170602_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfert',
            old_name='first_name',
            new_name='first_namesender',
        ),
        migrations.RenameField(
            model_name='transfert',
            old_name='last_name',
            new_name='last_namesender',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='guichet',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='user',
        ),
        migrations.AddField(
            model_name='transfert',
            name='guichet_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guichet_receiver', to='profiles.Guichet'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='guichet_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Guichet'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='user_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfert',
            name='user_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='MTCN',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code du Client'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='datereceiver',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reicever Date'),
        ),
    ]
