# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_auto_20170607_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='adressereceiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='adresse du destinataire'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='fonenumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='villereceiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ville du destinataire'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='villesender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ville de de l expediteur'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='MTCN',
            field=models.CharField(default='bonjour', max_length=12, unique=True, verbose_name='MTCN'),
            preserve_default=False,
        ),
    ]
