# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_auto_20170613_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='MTCN',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='MTCN'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='adressereceiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='adresse du         destinataire'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='cni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carte National Identite'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='commission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='fonenumber',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telephone'),
        ),
    ]
